### PR TITLE
[P69] Tile Defence

### PR DESCRIPTION
**Pull request by ewanharris**
https://trello.com/c/XG301JK9 

I'm pretty sure most flows are done, currently making a final pass to try and verify all flows. At a basic level
- ~~Unit selection prompt should be shown when you capture a tile~~
- ~~If you own a tile and it is not defended when you land on it then you should be prompted~~
- ~~No unit selection prompt if you only have 1 active unit~~
- ~~When a tile is defended a smaller version of the commander will be shown~~ (need opinions on size)
- ~~When a tile has been taken from the other player and the tile was defended, a smaller version of the commander will be shown~~ (need opinions on size)
- ~~When a unit is defending it is shown in the unit selection screen~~
- ~~When a unit is in jail it is shown in the unit selection screen~~ (the image **needs replacing** I just reused the defending one with some text)

### CODE REVIEW

**Comment by ewanharris** [comment]
Totally forgot to remove the WIP.....

**Comment by ewanharris** [comment]
Merged with master

**Comment by ewanharris** [comment]
Ping @alasdairhurst

**Comment by alasdairhurst** [comment]
@eharris93 I'll take a look!

**Comment by alasdairhurst** [comment]
@eharris93 merging. there's some bugs with taking tiles that beloing to other players/leaving units/taking prisoners/rescuing prisoners but can be sorted out in a new branch since it would be good to have this functionality in the master branch

**Pull request merged**
