### PR TITLE
[P56] Debug UI

### PR DESCRIPTION
**Pull request by MartinDawson**
https://trello.com/c/kIUt3ASl/70-p56-debug-ui

Added for review, debug fade + multiple messages.

### CODE REVIEW

**Comment by alasdairhurst** [comment]
@Yoshimiii Could you include a scene with it set up so that we can test it easily?

**Comment by MartinDawson** [comment]
To test it, call the SetMessage() method from wherever you want.

Also add as many text objects as u want

**Comment by alasdairhurst** [comment]
I noticed an issue where the UI panels interfere with the selection of the army UI below it. It was fixed by unchecking "interactable" and "blocks raycasts" from the canvas group on each text item.

**Comment by alasdairhurst** [comment]
FR/CR

**Pull request merged**
